### ISSUE TITLE
Potential issue with Alpha8 and joining games related to downloading new maps. 

### ISSUE THREAD

**Issue by Ephreaym** [opennox/opennox#601] opened 2023-08-07 02:13 UTC
Seems to be an issue with joining a game on Alpha8. Think it has to do with downloading maps. Pretty sure that when I send the mapfile via a third party and the person installs it the issue doesn't occur. 

Doesn't happen when people join with other cliënts, i.e. Reloaded.

**Comment by dennwc** [comment] 2023-08-13 09:36
Duplicate of #302

**Closed as completed by dennwc** 2023-08-13 09:36 UTC
Labels: T: Bug 🐛, M: Online :satellite:
