### ISSUE TITLE
Snap packaging breaks audio and Optimus graphics

### ISSUE THREAD

**Issue by Ishayu** [opennox/opennox#476] opened 2022-04-16 08:50 UTC
Hi OpenNox team,

Firstly, really impressed with what you've achieved, and thank you for putting it on Linux!
But it wasn't working out of the box.

**Environment:**
Razer Blade Advanced from 2021, RTX 2070 Max-Q with Optimus enabled.
Pop!_OS 21.10, X11 and Wayland both tried, GNOME desktop.
Report is for X11.

**Expected:**
Audio and graphics should work and the game should open normally.

**Observed:**
The game closes immediately when run - aka "nothing happens".

**Investigation:**
Running using the command line reveals this:
```christian@pop-os:/snap/opennox/49/bin$ opennox
2022/04/16 10:00:49 [version]: version: v1.8.9 ()
2022/04/16 10:00:49 [version]: GET https://ghcr.io/token?scope=repository%3Anoxworld-dev%2Fopennox%3Apull
2022/04/16 10:00:49 [config]: file not found, using defaults
2022/04/16 10:00:49 [gog]: potential install path: "/home/christian/Games/gog/nox/drive_c/GOG Games/Nox"
2022/04/16 10:00:49 [path]: cannot find required data file "gamedata.bin" in "/snap/opennox/49/bin"
2022/04/16 10:00:49 [path]: cannot find required data file "gamedata.bin" in "/snap/opennox/49/bin"
2022/04/16 10:00:49 [path]: setting data dir to: "/home/christian/Games/gog/nox/drive_c/GOG Games/Nox"
2022/04/16 10:00:49 [config]: writing to "/home/christian/snap/opennox/common/opennox.yml"
libGL error: MESA-LOADER: failed to open i965 (search paths /usr/lib/i386-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open i965 (search paths /usr/lib/i386-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: i965
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/i386-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 152 (GLX)
  Request Minor code 6 ()
  Error Serial #114
  Current Serial #113
```

Okay? Let's try running it in external graphics mode:
`__NV_PRIME_RENDER_OFFLOAD="1" __GLX_VENDOR_LIBRARY_NAME="nvidia" opennox`

Now the game launches, but this error appears and there is no sound:
```
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
```

Okay, it's looking for a file outside of the SNAP - but ideally it should be hijacked by the virtual file system. Evidently that alsa.conf is broken or the hardlinking isn't done correctly, and it can't read the real file. Either way, in a last ditch effort I copied the executable to $HOME and ran it manually.

The audio and graphics problems went away.

So I checked if audio playback was enabled, and it is:
```
Interface       Plug                    Slot             Notes
audio-playback  opennox:audio-playback  :audio-playback  -
```

Running the game by just double-clicking the executable inside the snap package, and not the one inside /snap/bin, makes the game work perfectly. Therefore, clearly, the problem is the snap container.

**Comment by dennwc** [comment] 2022-04-16 22:17
As the last paragraph implies, Snap confinement may be the cause. And if it's a Snap bug, we can't do anything about it from our side, unfortunately. Maybe #468 will fix it, or maybe not. Hard to tell at this point.

So I think we could close this and focus our discussion on #477 and/or #478 instead, to provide alternative packaging methods.

**Closed as completed by dennwc** 2022-04-16 22:17 UTC
Labels: T: Bug 🐛, P: Linux, A: Packaging 📦

**Comment by Ishayu** [comment] 2022-04-16 22:31
I completely agree with you. I see you’ve made some comments on Snap being controversial, and while I know that’s true, that’s not really part of the point I’m making. Obviously it can work since Chromium does, but it seems to be causing some headaches. I have no idea if it’s a bug in snap or not, although it certainly feels like one. 

Either way, I support whichever route you choose to go. DEB, RPM, AUR, FlatPak, AppImage, or even a fixed snap. 

Been playing it today. Really enjoying the nostalgia trip. :)

**Comment by Evengard** [comment] 2022-04-16 22:48
I like the AUR idea, btw... xD

**Comment by Ishayu** [comment] 2022-04-17 07:17
Haha. I use Arch Btw. Obviously. 

Jk. 

 No need to overdo it though. Linux packaging can be hell. I agree with the direction you’re going, but I do wish the snap was working honestly. 
 
Oh well. Thank you so much for looking into it. :)
