### ISSUE TITLE
snap install on Fedora37

### ISSUE THREAD

**Issue by droopy4096** [opennox/opennox#581] opened 2023-02-05 22:43 UTC
Having installed Nox from GOG with subsequently installing Snap, I'm getting odd errors:

```
2023/02/05 15:32:35 [version]: version: v1.8.11 ()
2023/02/05 15:32:35 [version]: GET https://ghcr.io/token?scope=repository%3Anoxworld-dev%2Fopennox%3Apull
2023/02/05 15:32:35 [config]: file not found, using defaults
2023/02/05 15:32:35 [gog]: potential install path: "/home/myuser/Games/gog/nox/drive_c/GOG Games/Nox"
2023/02/05 15:32:35 [path]: setting data dir to: "/home/myuser/Games/gog/nox/drive_c/GOG Games/Nox"
2023/02/05 15:32:35 [config]: writing to "/home/myuser/snap/opennox/common/opennox.yml"
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/i386-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/i386-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/i386-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 152 (GLX)
  Request Minor code 6 ()
  Error Serial #111
  Current Serial #110
```

**Comment by Evengard** [comment] 2023-02-06 02:40
Snap is kinda broken, I recommend trying flatpak: https://flathub.org/apps/details/io.github.noxworld_dev.OpenNox
Resolving theese 32 bit library errors in Snap is proving to be too troublesome and not troubleproof

**Comment by dennwc** [comment] 2023-02-07 21:19
Looks like a duplicate of #573.

**Closed as not planned by dennwc** 2023-02-07 21:19 UTC
Labels: P: Linux, A: Packaging 📦
